
baseURL = 'https://itclub-irk.ru/'
languageCode = 'ru-ru'
title = 'IT Club Irkutsk'

timeZone = "Asia/Irkutsk"

# theme = 'ace-documentation'
# theme = 'hugo-theme-bootstrap'

# https://themes.gohugo.io/themes/hugo-book/
theme = 'hugo-book'

[params]
  BookTheme = 'light'
