
baseURL = 'https://itclub-irk.ru/'
languageCode = 'en-us'
title = 'IT Club - Hugo Site'
# theme = 'ananke'
# theme = 'github-style'
theme = 'ace-documentation'
# theme = 'hugo-theme-bootstrap'
# theme = 'kraiklyn'
